language: csharp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      mono: latest
      dotnet: 1.0.1

script:
  - dotnet --info
  - dotnet restore
  - dotnet test ./tests/ZeroFormatter.FSharpExtensions.NETCore.Tests/ZeroFormatter.FSharpExtensions.NETCore.Tests.fsproj

